### ISSUE TITLE
Trezor lib not compatible any more

### ISSUE THREAD

**Issue by ghost** [8go/TrezorSymmetricFileEncryption#9]
Ubuntu18

`python3 TrezorSymmetricFileEncryption.py 
Traceback (most recent call last):
  File "TrezorSymmetricFileEncryption.py", line 22, in <module>
    from dialogs import Dialog
  File "/home/lekanovic/projects/TrezorSymmetricFileEncryption/dialogs.py", line 20, in <module>
    from processing import processAll
  File "/home/lekanovic/projects/TrezorSymmetricFileEncryption/processing.py", line 19, in <module>
    from trezorlib.client import CallException, PinException
ImportError: cannot import name 'CallException'`

looks like trezor has removed CallException in commit "06927e003e39834bef34ab0873a2fd4007159a38" in 	https://github.com/trezor/trezor-firmware.git

**Comment by qkum** [comment]
Did the project creator really fail in adding the original/working Trezor software to the repo...

So you could downgrade the software on your Trezor.

Anyways you should be able to find the old version with help of google. I found their archive a few weeks ago. The originals are available I'm sure as I saw them.

Just search for their "Developer" guide/documentation/wiki.

**Comment by qkum** [comment]
Someone could also update the software itself so it works with the newest Trezor software ofc. I assume that should possible, if not. It would point to Trezor not liking this kind of use of the Trezor and that seems unrealistic as it increases their sales.

**Comment by NazikXY** [comment]
I just tried to install the trezor library version 0.7.0 and suddenly everything worked

Immediately after installation, nothing worked, but I tried to install pyhton2.7 and trezorlib of the earliest versions, I failed. I tried to run through python3.9 again in despair and the miracle happened, I don't know what it's related to![image](https://user-images.githubusercontent.com/32540399/150690424-505246a0-9e71-439d-ae71-095774fb26f3.jpeg)

**Comment by 8go** [comment]
[TrezorSymmetricFileEncryption](https://github.com/8go/TrezorSymmetricFileEncryption) has not been updated in a long time. So, the trezorlib version is outdated, Python is outdated, etc. 

Yes, ideally, the software should be revised to bring it to Python 3.10 and the latest version of trezorlib, but unfortunately I don't have the time anymore to update this project. 

If there is somebody out there who volunteers to contribute a Pull Request to update this software, I would be happy to merge any PRs.

**Comment by m5x** [comment]
Just out of curiosity, can I ask what you use to encrypt files now? If my assumption that it's no longer Trezor and this project is correct...
